name: AzureML Job

on: 
  workflow_dispatch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:

    - name: Checkout Repository
      uses: actions/checkout@v4
      
    - name: Azure Login
      uses: azure/login@v2
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Install Azure Machine Learning extension
      run: |
        az extension add --name ml

    - name: Install distutils (to fix the missing module error)
      run: |
        sudo apt-get update
        sudo apt-get install python3-distutils

    - name: List repository structure
      run: |
        ls -R
        
    - name: Submit Azure ML job
      run: |
        az ml job create --file ./src/model/job.yml --resource-group newResource --workspace-name newWorkspace
